Repository IBM/nl2flow, pull requests merged in 2024-03, with the labels that each got.

#14 Generator wrapper
  profiler/converters/converter_variables.py
  profiler/converters/info_2_flow_converter.py
  profiler/data_types/generator_data_type.py
  profiler/generators/batch_data_generator/__init__.py
  profiler/generators/batch_data_generator/batch_data_generator.py
  profiler/generators/dataset_generator/dataset_generator.py
  profiler/generators/info_generator/agent_info_generator.py
  pyproject.toml
  tests/conftest/conftest.py
  tests/profiler/data_types/__init__.py
  tests/profiler/data_types/test_generator_data_type.py
  tests/profiler/generators/batch_data_generator/__init__.py
  tests/profiler/generators/batch_data_generator/test_batch_data_generator.py
Labels: enhancement, new feature

#29 iss19
  nl2flow/plan/planners.py
  nl2flow/plan/schemas.py
  nl2flow/plan/utils.py
Labels: bug

#35 iss33
  nl2flow/plan/planners.py
Labels: enhancement
