Repository IBM/nl2flow, pull requests merged in 2024-04, with the labels that each got.

#43 Remove TypedDict from NL2FLOW
  .gitignore
  profiler/converters/converter_variables.py
  profiler/converters/info_2_flow_converter.py
  profiler/data_types/agent_info_data_types.py
  profiler/data_types/generator_output_data_type.py
  profiler/generators/batch_data_generator/batch_data_generator.py
  profiler/generators/dataset_generator/dataset_generator.py
  profiler/generators/description_generator/description_generator.py
  profiler/generators/description_generator/description_generator_helper.py
  profiler/generators/info_generator/agent_info_generator_coupling_helper.py
  profiler/generators/info_generator/agent_info_generator_helper.py
  profiler/generators/info_generator/generator_variables.py
  profiler/validators/agent_info_generator_test_utils.py
  profiler/validators/validator_executer.py
  pyproject.toml
  tests/profiler/converters/test_info_2_flow_converter.py
  tests/profiler/generators/description_generator/test_description_generator_helper.py
  tests/profiler/generators/info_generator/test_agent_info_generator_helper.py
  tests/profiler/generators/info_generator/test_info_generator_coupling_helper.py
Labels: enhancement

#34 iss32
  nl2flow/compile/basic_compilations/compile_goals.py
  nl2flow/compile/basic_compilations/compile_operators.py
  nl2flow/compile/flow.py
  nl2flow/plan/options.py
  nl2flow/plan/planners.py
  nl2flow/plan/schemas.py
  nl2flow/plan/utils.py
  pyproject.toml
  tests/planner/__init__.py
  tests/planner/flags/__init__.py
  tests/planner/flags/test_flags.py
  tests/planner/formatting/__init__.py
  tests/planner/formatting/test_prettifier.py
  tests/profiler/generators/batch_data_generator/output.sas
Labels: bug

#52 Remove deprecated fields in AgentInfoSignatureItem
  profiler/data_types/agent_info_data_types.py
  tests/profiler/generators/description_generator/test_description_generator_helper.py
Labels: maintenance

#50 iss27
  nl2flow/compile/basic_compilations/compile_confirmation.py
  nl2flow/compile/basic_compilations/compile_constraints.py
  nl2flow/compile/basic_compilations/compile_goals.py
  nl2flow/compile/basic_compilations/compile_history.py
  nl2flow/compile/basic_compilations/compile_mappings.py
  nl2flow/compile/basic_compilations/compile_operators.py
  nl2flow/compile/basic_compilations/compile_reference.py
  nl2flow/compile/basic_compilations/compile_slots.py
  nl2flow/compile/basic_compilations/utils.py
  nl2flow/compile/compilations.py
  nl2flow/compile/flow.py
  nl2flow/compile/operators.py
  nl2flow/compile/options.py
  nl2flow/compile/schemas.py
  nl2flow/compile/utils.py
  nl2flow/debug/debug.py
  nl2flow/debug/schemas.py
  nl2flow/plan/planners.py
  nl2flow/plan/utils.py
  nl2flow/services/compilations/catalog_compilations.py
  nl2flow/services/compilations/sketch_compilations.py
  nl2flow/services/schemas/sketch_schemas.py
  tests/basic/test_basic_but_not_basic.py
  tests/constraints/test_constraints.py
  tests/debugger/__init__.py
  tests/debugger/test_debugger_from_flow.py
  tests/errors/test_duplicates.py
  tests/orderings/test_orderings.py
  tests/planner/formatting/test_prettifier.py
  tests/sketch/sample_catalogs/catalog.yaml
  tests/sketch/sample_sketches/07-sketch_with_constraints.yaml
  tests/sketch/sample_sketches/08-sketch_with_complex_goals.yaml
  tests/sketch/test_advanced_constraints.py
  tests/sketch/test_advanced_objects.py
  tests/sketch/test_basic.py
Labels: new feature

#61 pretty print refactor
  nl2flow/compile/basic_compilations/compile_goals.py
  nl2flow/compile/schemas.py
  nl2flow/debug/schemas.py
  nl2flow/plan/planners.py
  nl2flow/plan/schemas.py
  nl2flow/plan/utils.py
  tests/basic/test_basic_but_not_basic.py
  tests/constraints/test_constraints.py
  tests/debugger/test_debugger_from_flow.py
  tests/errors/test_duplicates.py
  tests/goals/test_and_or_goals.py
  tests/goals/test_goals_advanced.py
  tests/goals/test_goals_basic.py
  tests/history/test_history_progression.py
  tests/history/test_history_replan.py
  tests/mappings/test_mappings_advanced.py
  tests/mappings/test_mappings_basic.py
  tests/mappings/test_mappings_multi_instance.py
  tests/orderings/test_orderings.py
  tests/planner/flags/test_flags.py
  tests/planner/formatting/test_prettifier.py
  tests/retry/test_retry.py
  tests/sketch/test_advanced_constraints.py
  tests/sketch/test_advanced_objects.py
  tests/sketch/test_basic.py
  tests/slots/test_slots_advanced.py
  tests/slots/test_slots_basic.py
  tests/slots/test_slots_ordered.py
  tests/typing/test_typing_advanced.py
Labels: enhancement
